name: Docker Images CI

on:
  schedule:
  - cron: "0 2 * * 1-5"
  workflow_dispatch:


jobs:
  build-r1Core2:
    runs-on: ubuntu-latest

    steps:
    - name: Info
      run: |
       echo "Event type: ${{github.event_name}}"
    - name: Change docker to experimental mode
      run: |
       sudo rm -rf /etc/docker/daemon.json
       echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
    - name: Restart docker daemon
      run: sudo systemctl restart docker
    - uses: actions/checkout@v3
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      working-directory: docker_stuff/docker_core2/
      run: ./build-docker.sh
    - name: Push image
      run: docker push elandini84/r1images:r1Core2

################################################################## Currently runs OOM as the diffult containers for linux are 7Gb of RAM.
#   build-r1Sim2:
#     runs-on: ubuntu-latest
#     needs: build-r1Core2

#     steps:
#     - name: Change docker to experimental mode
#       run: |
#        sudo rm -rf /etc/docker/daemon.json
#        echo '{"experimental": true}' | sudo tee -a /etc/docker/daemon.json
#     - name: Restart docker daemon
#       run: sudo systemctl restart docker
#     - uses: actions/checkout@v3
#     - name: Login to Docker Hub
#       uses: docker/login-action@v2
#       with:
#         username: ${{ secrets.DOCKERHUB_USERNAME }}
#         password: ${{ secrets.DOCKERHUB_TOKEN }}
#     - name: Build the Docker image
#       working-directory: docker_stuff/docker_sim2/
#       run: ./build-docker.sh
#     - name: Push image
#       run: docker push konkarapas/r1images:r1Sim2
